version: '4.28'

services:
  db:
    image: mysql:latest
    container_name: herik-mysql
    restart: always
    environment:
      MYSQL_USER: herik
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: barbearia
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - volume-mysql-projetos:/var/lib/mysql

volumes:
  volume-mysql-projetos:
